/**
 * Copyright 2005-2014 Restlet
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: Apache 2.0 or or EPL 1.0 (the "Licenses"). You can
 * select the license that you prefer but you may not use this file except in
 * compliance with one of these Licenses.
 * 
 * You can obtain a copy of the Apache 2.0 license at
 * http://www.opensource.org/licenses/apache-2.0
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://restlet.com/products/restlet-framework
 * 
 * Restlet is a registered trademark of Restlet S.A.S.
 */

package ticketdbmodel;


import java.util.Date;
import ticketdbmodel.User;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:54613/Service.svc/$metadata">Metadata of the target OData service</a>
*
*/
public class Ticket {

    private Date createdAt;
    private String description;
    private int id;
    private int userId;
    private User user;

    /**
     * Constructor without parameter.
     * 
     */
    public Ticket() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public Ticket(int id) {
        this();
        this.id = id;
    }

   /**
    * Returns the value of the "createdAt" attribute.
    *
    * @return The value of the "createdAt" attribute.
    */
   public Date getCreatedAt() {
      return createdAt;
   }
   /**
    * Returns the value of the "description" attribute.
    *
    * @return The value of the "description" attribute.
    */
   public String getDescription() {
      return description;
   }
   /**
    * Returns the value of the "id" attribute.
    *
    * @return The value of the "id" attribute.
    */
   public int getId() {
      return id;
   }
   /**
    * Returns the value of the "userId" attribute.
    *
    * @return The value of the "userId" attribute.
    */
   public int getUserId() {
      return userId;
   }
   /**
    * Returns the value of the "user" attribute.
    *
    * @return The value of the "user" attribute.
    */
   public User getUser() {
      return user;
   }
   
   /**
    * Sets the value of the "createdAt" attribute.
    *
    * @param createdAt
    *     The value of the "createdAt" attribute.
    */
   public void setCreatedAt(Date createdAt) {
      this.createdAt = createdAt;
   }
   /**
    * Sets the value of the "description" attribute.
    *
    * @param description
    *     The value of the "description" attribute.
    */
   public void setDescription(String description) {
      this.description = description;
   }
   /**
    * Sets the value of the "id" attribute.
    *
    * @param id
    *     The value of the "id" attribute.
    */
   public void setId(int id) {
      this.id = id;
   }
   /**
    * Sets the value of the "userId" attribute.
    *
    * @param userId
    *     The value of the "userId" attribute.
    */
   public void setUserId(int userId) {
      this.userId = userId;
   }
   /**
    * Sets the value of the "user" attribute.
    *
    * @param user"
    *     The value of the "user" attribute.
    */
   public void setUser(User user) {
      this.user = user;
   }

}