/**
 * Copyright 2005-2014 Restlet
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: Apache 2.0 or or EPL 1.0 (the "Licenses"). You can
 * select the license that you prefer but you may not use this file except in
 * compliance with one of these Licenses.
 * 
 * You can obtain a copy of the Apache 2.0 license at
 * http://www.opensource.org/licenses/apache-2.0
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://restlet.com/products/restlet-framework
 * 
 * Restlet is a registered trademark of Restlet S.A.S.
 */

package ticketdbmodel;


import java.util.List;
import ticketdbmodel.Ticket;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:54613/Service.svc/$metadata">Metadata of the target OData service</a>
*
*/
public class User {

    private int id;
    private String name;
    private String username;
    private List<Ticket> tickets;

    /**
     * Constructor without parameter.
     * 
     */
    public User() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public User(int id) {
        this();
        this.id = id;
    }

   /**
    * Returns the value of the "id" attribute.
    *
    * @return The value of the "id" attribute.
    */
   public int getId() {
      return id;
   }
   /**
    * Returns the value of the "name" attribute.
    *
    * @return The value of the "name" attribute.
    */
   public String getName() {
      return name;
   }
   /**
    * Returns the value of the "username" attribute.
    *
    * @return The value of the "username" attribute.
    */
   public String getUsername() {
      return username;
   }
   /**
    * Returns the value of the "tickets" attribute.
    *
    * @return The value of the "tickets" attribute.
    */
   public List<Ticket> getTickets() {
      return tickets;
   }
   
   /**
    * Sets the value of the "id" attribute.
    *
    * @param id
    *     The value of the "id" attribute.
    */
   public void setId(int id) {
      this.id = id;
   }
   /**
    * Sets the value of the "name" attribute.
    *
    * @param name
    *     The value of the "name" attribute.
    */
   public void setName(String name) {
      this.name = name;
   }
   /**
    * Sets the value of the "username" attribute.
    *
    * @param username
    *     The value of the "username" attribute.
    */
   public void setUsername(String username) {
      this.username = username;
   }
   /**
    * Sets the value of the "tickets" attribute.
    *
    * @param tickets"
    *     The value of the "tickets" attribute.
    */
   public void setTickets(List<Ticket> tickets) {
      this.tickets = tickets;
   }

}